Exception on / [GET]
Traceback (most recent call last):
  File "C:\RK\projects\presences\env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\RK\projects\presences\env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\RK\projects\presences\env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\RK\projects\presences\env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\RK\projects\presences\app.py", line 106, in dashboard
    return render_template('dashboard.html', courses=courses, now=datetime.now())
  File "C:\RK\projects\presences\env\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\RK\projects\presences\env\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\RK\projects\presences\env\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\RK\projects\presences\env\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\RK\projects\presences\templates\dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\RK\projects\presences\templates\base.html", line 90, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\RK\projects\presences\templates\dashboard.html", line 23, in block 'content'
    <h5 class="card-title mb-0 fw-bold">{{ course.name }}</h5>
    ^
  File "C:\RK\projects\presences\env\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
  File "C:\RK\projects\presences\env\Lib\site-packages\sqlalchemy\orm\attributes.py", line 569, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\RK\projects\presences\env\Lib\site-packages\sqlalchemy\orm\attributes.py", line 1096, in get
    value = self._fire_loader_callables(state, key, passive)
  File "C:\RK\projects\presences\env\Lib\site-packages\sqlalchemy\orm\attributes.py", line 1126, in _fire_loader_callables
    return state._load_expired(state, passive)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\RK\projects\presences\env\Lib\site-packages\sqlalchemy\orm\state.py", line 803, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\RK\projects\presences\env\Lib\site-packages\sqlalchemy\orm\loading.py", line 1607, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
    ...<2 lines>...
    )
sqlalchemy.orm.exc.DetachedInstanceError: Instance <Course at 0x1dc863b92b0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Error accessing course: Instance <Course at 0x1daf41d51d0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Error accessing course: Instance <Course at 0x1daf41e7e30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Error accessing course: Instance <Course at 0x1daf4222d50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Error accessing course: Instance <Course at 0x1daf4207200> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Error accessing course: Instance <Course at 0x1daf4252f70> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Error accessing course: Instance <Course at 0x1daf42020a0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Error accessing course: Instance <Course at 0x1daf4287430> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Error accessing course: Instance <Course at 0x1daf4255550> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Error accessing course: Instance <Course at 0x1daf4289f60> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Error accessing course: Instance <Course at 0x1c2013eb110> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Error accessing course: Instance <Course at 0x1c2013f7e30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
Error accessing course: Instance <Course at 0x1c201431b50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
